import 'package:enum_to_string/enum_to_string.dart';

import '../../../neom_commons.dart';

class ActivityFeed {

  String id;
  String ownerId; ///Owner of activity feed
  String profileId; /// Reference to profile if needed
  String profileName; ///
  String profileImgUrl;
  String message;

  String activityReferenceId;
  ActivityFeedType?  activityFeedType;
  String mediaUrl;
  int createdTime;
  bool unread;

  ActivityFeed({
      this.id = "",
      this.ownerId = "",
      this.profileId = "",
      this.profileName = "",
      this.profileImgUrl = "",
      this.message = "",
      this.activityReferenceId = "",
      this.activityFeedType,
      this.mediaUrl = "",
      this.createdTime = 0,
      this.unread = true
  });

  ActivityFeed.fromJSON(data) :
        id = data["id"] ?? "",
        ownerId = data["ownerId"] ?? "",
        profileId = data["profileId"] ?? "",
        profileName = data["profileName"] ?? "",
        profileImgUrl = data["profileImgUrl"] ?? "",
        message = data["message"] ?? "",
        activityReferenceId = data["activityReferenceId"] ?? "",
        activityFeedType = EnumToString.fromString(ActivityFeedType.values, data["activityFeedType"] ?? ActivityFeedType.comment.name),
        mediaUrl = data["mediaUrl"] ?? "",
        createdTime = data["createdTime"] ?? 0,
        unread = data["unread"] ?? true;

  Map<String, dynamic>  toJSON()=>{
//    'id': id, //generated by firebase
    'ownerId': ownerId,
    'profileId': profileId,
    'profileName': profileName,
    'profileImgUrl': profileImgUrl,
    'message': message,
    'activityReferenceId': activityReferenceId,
    'activityFeedType': activityFeedType?.name ?? "",
    'mediaUrl': mediaUrl,
    'createdTime': createdTime,
    'unread': unread,
  };

  Map<String, dynamic>  toJSONWithId()=>{
    'id': id,
    'ownerId': ownerId,
    'profileId': profileId,
    'profileName': profileName,
    'profileImgUrl': profileImgUrl,
    'message': message,
    'activityReferenceId': activityReferenceId,
    'activityFeedType': activityFeedType?.name ?? "",
    'mediaUrl': mediaUrl,
    'createdTime': createdTime,
    'unread': unread,
  };

  ActivityFeed.fromEvent({required Event event, required AppProfile fromProfile,
    required ActivityFeedType type, String msg = ''}) :
        id = '',
        ownerId = event.ownerId,
        activityReferenceId = event.id,
        mediaUrl = event.imgUrl,
        profileId = fromProfile.id,
        profileName = fromProfile.name,
        profileImgUrl = fromProfile.photoUrl,
        activityFeedType = type,
        createdTime = DateTime.now().millisecondsSinceEpoch,
        message = msg,
        unread = true;

  ActivityFeed.fromPost({required Post post, required AppProfile fromProfile,
    required ActivityFeedType type, String msg = ''}) :
        id = '',
        ownerId = post.ownerId,
        activityReferenceId = post.id,
        mediaUrl = post.mediaUrl,
        profileId = fromProfile.id,
        profileName = fromProfile.name,
        profileImgUrl = fromProfile.photoUrl,
        activityFeedType = type,
        createdTime = DateTime.now().millisecondsSinceEpoch,
        message = msg,
        unread = true;

  ActivityFeed.fromComment({required PostComment comment, required ActivityFeedType type,
    AppProfile? fromProfile, String? mediaUrl}) :
        id = '',
        ownerId = comment.ownerId,
        activityReferenceId = comment.postId,
        mediaUrl = mediaUrl ?? comment.mediaUrl,
        profileId = fromProfile?.id ?? comment.ownerId,
        profileName = fromProfile?.name ?? comment.ownerName,
        profileImgUrl = fromProfile?.photoUrl ?? comment.ownerImgUrl,
        activityFeedType = type,
        createdTime = DateTime.now().millisecondsSinceEpoch,
        message = comment.text,
        unread = true;

  ActivityFeed.fromRequest({required AppRequest request, required ActivityFeedType type,
    required AppProfile fromProfile, this.mediaUrl = '', bool isResponse = false,
    bool isEvent = true, String? message}) :
        id = '',
        ownerId = isResponse ? request.from : request.to,
        activityReferenceId = isEvent ? request.eventId : request.bandId,
        profileId = fromProfile.id,
        profileName = fromProfile.name,
        profileImgUrl = fromProfile.photoUrl,
        activityFeedType = type,
        createdTime = DateTime.now().millisecondsSinceEpoch,
        message = message ?? request.message,
        unread = true;

  ActivityFeed.fromAppBot({required String toProfileId, required referenceId,
    required ActivityFeedType type, this.message = '', this.mediaUrl = ''}) :
        id = '',
        ownerId = toProfileId,
        activityReferenceId = referenceId,
        profileId = AppConstants.appBot,
        profileName = "${AppFlavour.getAppName()} ${AppConstants.appBotName}",
        profileImgUrl = AppFlavour.getAppLogoUrl(),
        activityFeedType = type,
        createdTime = DateTime.now().millisecondsSinceEpoch,
        unread = true;
}
