import 'package:enum_to_string/enum_to_string.dart';

import '../../utils/enums/activity_feed_type.dart';

class ActivityFeed {

  String id;
  String ownerId; ///Owner of activity feed
  String profileId; /// Reference to profile if needed
  String profileName; ///
  String profileImgUrl;
  String message;

  String activityReferenceId;
  ActivityFeedType?  activityFeedType;
  String mediaUrl;
  int createdTime;
  bool unread;

  ActivityFeed({
      this.id = "",
      this.ownerId = "",
      this.profileId = "",
      this.profileName = "",
      this.profileImgUrl = "",
      this.message = "",
      this.activityReferenceId = "",
      this.activityFeedType,
      this.mediaUrl = "",
      this.createdTime = 0,
      this.unread = true
  });

  ActivityFeed.fromJSON(data) :
        id = data["id"] ?? "",
        ownerId = data["ownerId"] ?? "",
        profileId = data["profileId"] ?? "",
        profileName = data["profileName"] ?? "",
        profileImgUrl = data["profileImgUrl"] ?? "",
        message = data["message"] ?? "",
        activityReferenceId = data["activityReferenceId"] ?? "",
        activityFeedType = EnumToString.fromString(ActivityFeedType.values, data["activityFeedType"] ?? ActivityFeedType.comment.name),
        mediaUrl = data["mediaUrl"] ?? "",
        createdTime = data["createdTime"] ?? 0,
        unread = data["unread"] ?? true;

  Map<String, dynamic>  toJSON()=>{
//    'id': id, //generated by firebase
    'ownerId': ownerId,
    'profileId': profileId,
    'profileName': profileName,
    'profileImgUrl': profileImgUrl,
    'message': message,
    'activityReferenceId': activityReferenceId,
    'activityFeedType': activityFeedType?.name ?? "",
    'mediaUrl': mediaUrl,
    'createdTime': createdTime,
    'unread': unread,
  };

}
