import 'package:get/get.dart';

import '../../utils/constants/app_constants.dart';
import '../../utils/constants/app_translation_constants.dart';
import '../../utils/core_utilities.dart';
import 'app_item.dart';

class Itemlist {

  String id; //Generated by firestore or spotify Playlist Id
  String name;
  String description = "";
  String href;
  String imgUrl;
  bool public;
  String uri; // A link to the Web API endpoint providing full details of the playlist.
  List<AppItem>? appItems;
  bool isFav = false;

  Itemlist({
    this.id = "",
    this.name = "",
    this.description = "",
    this.href = "",
    this.imgUrl = "",
    this.public = true,
    this.uri = "",
    this.appItems,
    this.isFav = false
  });


  Itemlist.myFirstGigList() :
    id = AppConstants.firstItemlist,
    name = AppTranslationConstants.myFirstItemlistName.tr,
    description = AppTranslationConstants.myFirstItemlistDesc.tr,
    href = "",
    imgUrl = "",
    public = true,
    uri = "",
    appItems = CoreUtilities.myFirstAppItem(),
    isFav = true;


  Itemlist.myFirstGigListFan() :
        id = AppConstants.firstItemlist,
        name = AppTranslationConstants.myFirstItemlistName.tr,
        description = AppTranslationConstants.myFirstItemlistFanDesc.tr,
        href = "",
        imgUrl = "",
        public = true,
        uri = "",
        appItems = CoreUtilities.myFirstAppItem(),
        isFav = true;


  Itemlist.createBasic(this.name, desc) :
    id = "",
    description = desc,
    href = "",
    imgUrl = "",
    public = true,
    uri = "",
    appItems = [],
    isFav = false;


  Itemlist.fromJSON(data) :
    id = data["id"] ?? "",
    name = data["name"] ?? "",
    description = data["description"] ?? "",
    href = data["href"] ?? "",
    imgUrl = data["imgUrl"] ?? "",
    public = data["public"] ?? true,
    uri = data["uri"],
    isFav = data["isFav"] ?? false,
    appItems =  data["appItems"]?.map<AppItem>((item) {
      return AppItem.fromJSON(item);
    }).toList() ?? data["songs"]?.map<AppItem>((item) {
      return AppItem.fromJSON(item);
    }).toList() ?? [];


  @override
  String toString() {
    return 'Itemlist{id: $id, name: $name, description: $description, href: $href, imgUrl: $imgUrl, public: $public, uri: $uri, appItems: $appItems, isFav: $isFav}';
  }

  Map<String, dynamic>  toJSON()=>{
    //'id': id, generated in firebase
    'name': name,
    'description': description,
    'href': href,
    'imgUrl': imgUrl,
    'public': public,
    'uri': uri,
    'appItem': appItems!.map((appItem) => appItem.toJSON()).toList(),
    'isFav': isFav
  };

}
