import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:enum_to_string/enum_to_string.dart';

import '../../utils/enums/reference_type.dart';
import '../../utils/enums/report_type.dart';


class Report {

  String id;
  String ownerId;
  ReportType type;
  String referenceId;
  ReferenceType referenceType;
  int createdTime;
  int modifiedTime;
  String message;
  bool processed = false;

  Report({
    this.id = "",
    this.ownerId = "",
    this.type = ReportType.other,
    this.referenceId = "",
    this.referenceType = ReferenceType.post,
    this.createdTime = 0,
    this.modifiedTime = 0,
    this.message = ""});


  @override
  String toString() {
    return 'Report{id: $id, ownerId: $ownerId, type: $type, referenceId: $referenceId, referenceType: $referenceType, createdTime: $createdTime, modifiedTime: $modifiedTime, message: $message, processed: $processed}';
  }

  Report.fromDocumentSnapshot({required DocumentSnapshot documentSnapshot}) :
    id = documentSnapshot.id,
    ownerId = documentSnapshot.get("ownerId"),
    type = EnumToString.fromString(ReportType.values, documentSnapshot.get("type")) ?? ReportType.other,
    referenceId = documentSnapshot.get("referenceId"),
    referenceType = documentSnapshot.get("referenceType"),
    createdTime = documentSnapshot.get("createdTime"),
    modifiedTime = documentSnapshot.get("modifiedTime"),
    message = documentSnapshot.get("message");

  Map<String, dynamic> toJSON()=>{
    //'postId': postId, //generated by firebase
    'ownerId': ownerId,
    'type': type.name,
    'referenceId': referenceId,
    'referenceType': referenceType.name,
    'createdTime': createdTime,
    'modifiedTime': modifiedTime,
    'message': message,
    'processed': processed,
  };


}
