import 'dart:convert';

import 'package:enum_to_string/enum_to_string.dart';
import 'package:geolocator/geolocator.dart';

import '../../utils/neom_logger.dart';
import '../../utils/position_parser.dart';
import '../../utils/enums/itemlist_type.dart';
import '../../utils/enums/owner_type.dart';
import 'app_media_item.dart';
import 'app_release_item.dart';
import 'external_item.dart';

class Itemlist {

  String id; ///Generated by firestore or third-party playlist Id
  String slug;
  String name;
  String description;
  String ownerId;
  String ownerName;
  OwnerType ownerType;
  String href; ///Reference to something in future
  String imgUrl;
  bool public;
  Position? position;
  bool isModifiable;

  List<AppReleaseItem>? appReleaseItems;
  List<AppMediaItem>? appMediaItems;
  List<ExternalItem>? externalItems;
  String uri; /// A link to the Web API endpoint providing full details of the external list.
  ItemlistType type;

  String dominantColor;
  int tracksCount;
  int totalDuration;
  bool isExplicit;
  String upc;

  int? createdTime; ///CREATED TIME ON PLATFORM
  int? modifiedTime; ///TIME OF LAST MODIFICATION
  String? language; ///SPANISH - ENGLISH - ETC

  List<String>? categories; ///CATEGORIES FOR BOOKS | SONGS | PODCASTS | CATEGORIES RETRIEVED FROM WC
  List<String>? tags; ///TAGS OR GENRES FOR BOOKS | SONGS | PODCASTS | TAGS RETRIEVED FROM WC

  Itemlist({
    this.id = "",
    this.slug = "",
    this.name = "",
    this.description = "",
    this.ownerId = "",
    this.ownerName = "",
    this.ownerType = OwnerType.profile,
    this.href = "",
    this.imgUrl = "",
    this.public = true,
    this.position,
    this.isModifiable = true,
    this.appReleaseItems,
    this.appMediaItems,
    this.externalItems,
    this.uri = "",
    this.type = ItemlistType.playlist,
    this.createdTime,
    this.modifiedTime,
    this.language = "",
    this.categories,
    this.tags,
    this.dominantColor = "",
    this.tracksCount = 0,
    this.totalDuration = 0,
    this.isExplicit = false,
    this.upc = "",
  });

  @override
  String toString() {
    return 'Itemlist{id: $id, name: $name, description: $description, ownerId: $ownerId, ownerName: $ownerName, ownerType: $ownerType, href: $href, imgUrl: $imgUrl, public: $public, position: $position, isModifiable: $isModifiable, appReleaseItems: $appReleaseItems, appMediaItems: $appMediaItems, externalItems: $externalItems, uri: $uri, type: $type}';
  }

  Itemlist.createBasic(this.name, desc, this.ownerId, this.ownerName, this.type) :
    id = "",
    slug = "",
    description = desc,
    href = "",
    imgUrl = "",
    public = true,
    uri = "",
    ownerType = OwnerType.profile,
    appReleaseItems = [],
    appMediaItems = [],
    isModifiable = true,
    dominantColor = "",
    tracksCount = 0,
    totalDuration = 0,
    isExplicit = false,
    upc = "";

  Itemlist.fromJSON(dynamic data) :
    id = data["id"] ?? "",
    slug = data["slug"] ?? "",
    name = data["name"] ?? "",
    description = data["description"] ?? "",
    href = data["href"] ?? "",
    imgUrl = data["imgUrl"] ?? "",
    public = data["public"] ?? true,
    isModifiable = data["isModifiable"] ?? true,
    ownerId = data["ownerId"] ?? "",
    ownerName = data["ownerName"] ?? "",
    uri = data["uri"],
    appReleaseItems = data["appReleaseItems"]?.map<AppReleaseItem>((item) {
      return AppReleaseItem.fromJSON(item);
    }).toList() ?? [],
    appMediaItems =  data["appMediaItems"]?.map<AppMediaItem>((item) {
      return AppMediaItem.fromJSON(item);
    }).toList(),
    externalItems = data["externalItems"]?.map<ExternalItem>((item) {
      return ExternalItem.fromJSON(item);
    }).toList() ?? [],
    position = PositionParser.JSONtoPosition(data["position"]),
    type = EnumToString.fromString(ItemlistType.values, data["type"] ?? ItemlistType.playlist.name) ?? ItemlistType.playlist,
    ownerType = EnumToString.fromString(OwnerType.values, data["ownerType"] ?? OwnerType.profile.name) ?? OwnerType.profile,
    createdTime = data["createdTime"],
    modifiedTime = data["modifiedTime"],
    language = data["language"] ?? "",
    categories = List.from(data["categories"]?.cast<String>() ?? []),
    tags = List.from(data["tags"]?.cast<String>() ?? []),
    dominantColor = data["dominantColor"] ?? "",
    tracksCount = data["tracksCount"] ?? 0,
    totalDuration = data["totalDuration"] ?? 0,
    isExplicit = data["isExplicit"] ?? false,
    upc = data["upc"] ?? "";

  Map<String, dynamic> toJSON()=>{
    //'id': id, generated in firebase
    'slug': slug,
    'name': name,
    'description': description,
    'href': href,
    'imgUrl': imgUrl,
    'ownerId': ownerId,
    'ownerName': ownerName,
    'public': public,
    'uri': uri,
    'appReleaseItems': appReleaseItems?.map((appReleaseItem) => appReleaseItem.toJSON()).toList() ?? [],
    'appMediaItems': appMediaItems?.map((appMediaItem) => appMediaItem.toJSON()).toList() ?? [],
    'externalItems': externalItems?.map((externalItem) => externalItem.toJSON()).toList() ?? [],
    'position': jsonEncode(position),
    'type': type.name,
    'ownerType': ownerType.name,
    'isModifiable': isModifiable,
    'createdTime': createdTime,
    'modifiedTime': modifiedTime,
    'language': language,
    'categories': categories,
    'tags': tags,
    'dominantColor': dominantColor,
    'tracksCount': tracksCount,
    'totalDuration': totalDuration,
    'isExplicit': isExplicit,
    'upc': upc
  };

  Map<String, dynamic> toJSONWithID()=>{
    'id': id,
    'slug': slug,
    'name': name,
    'description': description,
    'href': href,
    'imgUrl': imgUrl,
    'ownerId': ownerId,
    'ownerName': ownerName,
    'public': public,
    'uri': uri,
    'appMediaItems': appMediaItems?.map((appMediaItem) => appMediaItem.toJSON()).toList() ?? [],
    'appReleaseItems': appReleaseItems?.map((appReleaseItem) => appReleaseItem.toJSON()).toList() ?? [],
    'externalItems': externalItems?.map((externalItem) => externalItem.toJSON()).toList() ?? [],
    'position': position != null ? jsonEncode(position) : null,
    'type': type.name,
    'ownerType': ownerType.name,
    'isModifiable': isModifiable,
    'createdTime': createdTime,
    'modifiedTime': modifiedTime,
    'language': language,
    'categories': categories,
    'tags': tags,
    'dominantColor': dominantColor,
    'tracksCount': tracksCount,
    'totalDuration': totalDuration,
    'isExplicit': isExplicit,
    'upc': upc
  };

  List<dynamic> get allItems {
    final List<dynamic> combinedList = [];

    if (appReleaseItems != null) combinedList.addAll(appReleaseItems!);
    if (appMediaItems != null) combinedList.addAll(appMediaItems!);
    if (externalItems != null) combinedList.addAll(externalItems!);

    return combinedList;
  }

  int getTotalItems() {
    int totalItems = allItems.length;
    neomLogger.t("Retrieving $totalItems Total Items.");
    return totalItems;
  }

  List<String> getImgUrls() {

    Set<String> imgUrls = {};

    if(imgUrl.isNotEmpty) imgUrls.add(imgUrl);

    for (var item in allItems) {
      String currentImgUrl = '';
      List<String>? galleryUrls;

      if (item is AppReleaseItem) {
        currentImgUrl = item.imgUrl;
        galleryUrls = item.galleryUrls;
      } else if (item is AppMediaItem) {
        currentImgUrl = item.imgUrl;
        galleryUrls = item.galleryUrls;
      } else if (item is ExternalItem) {
        currentImgUrl = item.imgUrl;
        galleryUrls = item.galleryUrls;
      }

      if(currentImgUrl.isNotEmpty) {
        imgUrls.add(currentImgUrl);
      } else if(galleryUrls?.isNotEmpty ?? false) {
        imgUrls.add(galleryUrls!.first);
      }
    }

    neomLogger.t("Retrieving ${imgUrls.length} total Images for itemlist $name.");
    return imgUrls.toList();
  }

  dynamic getItem(String itemId) {
    if (itemId.isEmpty) {
      neomLogger.w("Item ID cannot be empty when searching itemlist: $name");
      return null;
    }

    dynamic foundItem = allItems.firstWhere((item) {
      return item.id == itemId;
    });

    return foundItem;
  }

}
