import 'package:intl_phone_field/countries.dart';

class IntlPhoneConstants {

  static String initialCountryCode = 'MX';

  static List<Country> availableCountries = [
    const Country(
      name: "Mexico",
      nameTranslations: {
        "sk": "Mexiko",
        "se": "Meksiko",
        "pl": "Meksyk",
        "no": "Mexico",
        "ja": "メキシコ",
        "it": "Messico",
        "zh": "墨西哥",
        "nl": "Mexico",
        "de": "Mexiko",
        "fr": "Mexique",
        "es": "México",
        "en": "Mexico",
        "pt_BR": "México",
        "sr-Cyrl": "Мексико",
        "sr-Latn": "Meksiko",
        "zh_TW": "墨西哥",
        "tr": "Meksika",
        "ro": "Mexic",
        "ar": "المكسيك",
        "fa": "مکزیک",
        "yue": "墨西哥"
      },
      flag: "🇲🇽",
      code: "MX",
      dialCode: "52",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "Argentina",
      nameTranslations: {
        "sk": "Argentína",
        "se": "Argentina",
        "pl": "Argentyna",
        "no": "Argentina",
        "ja": "アルゼンチン",
        "it": "Argentina",
        "zh": "阿根廷",
        "nl": "Argentinië",
        "de": "Argentinien",
        "fr": "Argentine",
        "es": "Argentina",
        "en": "Argentina",
        "pt_BR": "Argentina",
        "sr-Cyrl": "Аргентина",
        "sr-Latn": "Argentina",
        "zh_TW": "阿根廷",
        "tr": "Arjantin",
        "ro": "Argentina",
        "ar": "الأرجنتين",
        "fa": "آرژانتین",
        "yue": "阿根廷"
      },
      flag: "🇦🇷",
      code: "AR",
      dialCode: "54",
      minLength: 12,
      maxLength: 12,
    ),
    const Country(
      name: "Bolivia, Plurinational State of bolivia",
      nameTranslations: {
        "sk": "Bolívia",
        "se": "Bolivia",
        "pl": "Boliwia",
        "no": "Bolivia",
        "ja": "ボリビア",
        "it": "Bolivia",
        "zh": "玻利维亚",
        "nl": "Bolivia",
        "de": "Bolivien",
        "fr": "Bolivie",
        "es": "Bolivia",
        "en": "Bolivia",
        "pt_BR": "Bolívia",
        "sr-Cyrl": "Боливија",
        "sr-Latn": "Bolivija",
        "zh_TW": "玻利維亞",
        "tr": "Bolivya",
        "ro": "Bolivia",
        "ar": "بوليفيا",
        "fa": "بولیوی",
        "yue": "玻利維亞（多民族國家）"
      },
      flag: "🇧🇴",
      code: "BO",
      dialCode: "591",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Brazil",
      nameTranslations: {
        "sk": "Brazília",
        "se": "Brasil",
        "pl": "Brazylia",
        "no": "Brasil",
        "ja": "ブラジル",
        "it": "Brasile",
        "zh": "巴西",
        "nl": "Brazilië",
        "de": "Brasilien",
        "fr": "Brésil",
        "es": "Brasil",
        "en": "Brazil",
        "pt_BR": "Brasil",
        "sr-Cyrl": "Бразил",
        "sr-Latn": "Brazil",
        "zh_TW": "巴西",
        "tr": "Brezilya",
        "ro": "Brazilia",
        "ar": "البرازيل",
        "fa": "برزیل",
        "yue": "巴西"
      },
      flag: "🇧🇷",
      code: "BR",
      dialCode: "55",
      minLength: 11,
      maxLength: 11,
    ),
    const Country(
      name: "Canada",
      nameTranslations: {
        "sk": "Kanada",
        "se": "Kanáda",
        "pl": "Kanada",
        "no": "Canada",
        "ja": "カナダ",
        "it": "Canada",
        "zh": "加拿大",
        "nl": "Canada",
        "de": "Kanada",
        "fr": "Canada",
        "es": "Canadá",
        "en": "Canada",
        "pt_BR": "Canadá",
        "sr-Cyrl": "Канада",
        "sr-Latn": "Kanada",
        "zh_TW": "加拿大",
        "tr": "Kanada",
        "ro": "Canada",
        "ar": "كندا",
        "fa": "کانادا",
        "yue": "加拿大"
      },
      flag: "🇨🇦",
      code: "CA",
      dialCode: "1",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "Chile",
      nameTranslations: {
        "sk": "Čile",
        "se": "Čiile",
        "pl": "Chile",
        "no": "Chile",
        "ja": "チリ",
        "it": "Cile",
        "zh": "智利",
        "nl": "Chili",
        "de": "Chile",
        "fr": "Chili",
        "es": "Chile",
        "en": "Chile",
        "pt_BR": "Chile",
        "sr-Cyrl": "Чиле",
        "sr-Latn": "Čile",
        "zh_TW": "智利",
        "tr": "Şili",
        "ro": "Chile",
        "ar": "تشيلي",
        "fa": "شیلی",
        "yue": "智利"
      },
      flag: "🇨🇱",
      code: "CL",
      dialCode: "56",
      minLength: 9,
      maxLength: 9,
    ),
    const Country(
      name: "Colombia",
      nameTranslations: {
        "sk": "Kolumbia",
        "se": "Kolombia",
        "pl": "Kolumbia",
        "no": "Colombia",
        "ja": "コロンビア",
        "it": "Colombia",
        "zh": "哥伦比亚",
        "nl": "Colombia",
        "de": "Kolumbien",
        "fr": "Colombie",
        "es": "Colombia",
        "en": "Colombia",
        "pt_BR": "Colômbia",
        "sr-Cyrl": "Колумбија",
        "sr-Latn": "Kolumbija",
        "zh_TW": "哥倫比亞",
        "tr": "Kolombiya",
        "ro": "Columbia",
        "ar": "كولومبيا",
        "fa": "کلمبیا",
        "yue": "哥倫比亞"
      },
      flag: "🇨🇴",
      code: "CO",
      dialCode: "57",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "Costa Rica",
      nameTranslations: {
        "sk": "Kostarika",
        "se": "Costa Rica",
        "pl": "Kostaryka",
        "no": "Costa Rica",
        "ja": "コスタリカ",
        "it": "Costa Rica",
        "zh": "哥斯达黎加",
        "nl": "Costa Rica",
        "de": "Costa Rica",
        "fr": "Costa Rica",
        "es": "Costa Rica",
        "en": "Costa Rica",
        "pt_BR": "Costa Rica",
        "sr-Cyrl": "Коста Рика",
        "sr-Latn": "Kosta Rika",
        "zh_TW": "哥斯大黎加",
        "tr": "Kosta Rika",
        "ro": "Costa Rica",
        "ar": "كوستاريكا",
        "fa": "کاستاریکا",
        "yue": "哥斯達黎加"
      },
      flag: "🇨🇷",
      code: "CR",
      dialCode: "506",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Cuba",
      nameTranslations: {
        "sk": "Kuba",
        "se": "Kuba",
        "pl": "Kuba",
        "no": "Cuba",
        "ja": "キューバ",
        "it": "Cuba",
        "zh": "古巴",
        "nl": "Cuba",
        "de": "Kuba",
        "fr": "Cuba",
        "es": "Cuba",
        "en": "Cuba",
        "pt_BR": "Cuba",
        "sr-Cyrl": "Куба",
        "sr-Latn": "Kuba",
        "zh_TW": "古巴",
        "tr": "Küba",
        "ro": "Cuba",
        "ar": "كوبا",
        "fa": "كوبا",
        "yue": "古巴"
      },
      flag: "🇨🇺",
      code: "CU",
      dialCode: "53",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Ecuador",
      nameTranslations: {
        "sk": "Ekvádor",
        "se": "Ecuador",
        "pl": "Ekwador",
        "no": "Ecuador",
        "ja": "エクアドル",
        "it": "Ecuador",
        "zh": "厄瓜多尔",
        "nl": "Ecuador",
        "de": "Ecuador",
        "fr": "Équateur",
        "es": "Ecuador",
        "en": "Ecuador",
        "pt_BR": "Equador",
        "sr-Cyrl": "Еквадор",
        "sr-Latn": "Ekvador",
        "zh_TW": "厄瓜多",
        "tr": "Ekvador",
        "ro": "Ecuador",
        "ar": "الإكوادور",
        "fa": "اكوادور",
        "yue": "厄瓜多爾"
      },
      flag: "🇪🇨",
      code: "EC",
      dialCode: "593",
      minLength: 8,
      maxLength: 9,
    ),
    const Country(
      name: "El Salvador",
      nameTranslations: {
        "sk": "Salvádor",
        "se": "El Salvador",
        "pl": "Salwador",
        "no": "El Salvador",
        "ja": "エルサルバドル",
        "it": "El Salvador",
        "zh": "萨尔瓦多",
        "nl": "El Salvador",
        "de": "El Salvador",
        "fr": "Salvador",
        "es": "El Salvador",
        "en": "El Salvador",
        "pt_BR": "El Salvador",
        "sr-Cyrl": "Салвадор",
        "sr-Latn": "Salvador",
        "zh_TW": "薩爾瓦多",
        "tr": "El Salvador",
        "ro": "Salvador",
        "ar": "السلفادور",
        "fa": "ال سالوادور",
        "yue": "薩爾瓦多"
      },
      flag: "🇸🇻",
      code: "SV",
      dialCode: "503",
      minLength: 11,
      maxLength: 11,
    ),
    const Country(
      name: "France",
      nameTranslations: {
        "sk": "Francúzsko",
        "se": "Frankriika",
        "pl": "Francja",
        "no": "Frankrike",
        "ja": "フランス",
        "it": "Francia",
        "zh": "法国",
        "nl": "Frankrijk",
        "de": "Frankreich",
        "fr": "France",
        "es": "Francia",
        "en": "France",
        "pt_BR": "França",
        "sr-Cyrl": "Француска",
        "sr-Latn": "Francuska",
        "zh_TW": "法國",
        "tr": "Fransa",
        "ro": "Franța",
        "ar": "فرنسا",
        "fa": "فرانسه",
        "yue": "法國"
      },
      flag: "🇫🇷",
      code: "FR",
      dialCode: "33",
      minLength: 9,
      maxLength: 9,
    ),
    const Country(
      name: "Germany",
      nameTranslations: {
        "sk": "Nemecko",
        "se": "Duiska",
        "pl": "Niemcy",
        "no": "Tyskland",
        "ja": "ドイツ",
        "it": "Germania",
        "zh": "德国",
        "nl": "Duitsland",
        "de": "Deutschland",
        "fr": "Allemagne",
        "es": "Alemania",
        "en": "Germany",
        "pt_BR": "Alemanha",
        "sr-Cyrl": "Немачка",
        "sr-Latn": "Nemačka",
        "zh_TW": "德國",
        "tr": "Almanya",
        "ro": "Germania",
        "ar": "ألمانيا",
        "fa": "آلمان",
        "yue": "德國"
      },
      flag: "🇩🇪",
      code: "DE",
      dialCode: "49",
      minLength: 9,
      maxLength: 13,
    ),
    const Country(
      name: "Guatemala",
      nameTranslations: {
        "sk": "Guatemala",
        "se": "Guatemala",
        "pl": "Gwatemala",
        "no": "Guatemala",
        "ja": "グアテマラ",
        "it": "Guatemala",
        "zh": "危地马拉",
        "nl": "Guatemala",
        "de": "Guatemala",
        "fr": "Guatemala",
        "es": "Guatemala",
        "en": "Guatemala",
        "pt_BR": "Guatemala",
        "sr-Cyrl": "Гватемала",
        "sr-Latn": "Gvatemala",
        "zh_TW": "瓜地馬拉",
        "tr": "Guatemala",
        "ro": "Guatemala",
        "ar": "غواتيمالا",
        "fa": "گواتمالا",
        "yue": "危地馬拉"
      },
      flag: "🇬🇹",
      code: "GT",
      dialCode: "502",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Haiti",
      nameTranslations: {
        "sk": "Haiti",
        "se": "Haiti",
        "pl": "Haiti",
        "no": "Haiti",
        "ja": "ハイチ",
        "it": "Haiti",
        "zh": "海地",
        "nl": "Haïti",
        "de": "Haiti",
        "fr": "Haïti",
        "es": "Haití",
        "en": "Haiti",
        "pt_BR": "Haiti",
        "sr-Cyrl": "Хаити",
        "sr-Latn": "Haiti",
        "zh_TW": "海地",
        "tr": "Haiti",
        "ro": "Haiti",
        "ar": "هايتي",
        "fa": "هائیتی",
        "yue": "海地"
      },
      flag: "🇭🇹",
      code: "HT",
      dialCode: "509",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Honduras",
      nameTranslations: {
        "sk": "Honduras",
        "se": "Honduras",
        "pl": "Honduras",
        "no": "Honduras",
        "ja": "ホンジュラス",
        "it": "Honduras",
        "zh": "洪都拉斯",
        "nl": "Honduras",
        "de": "Honduras",
        "fr": "Honduras",
        "es": "Honduras",
        "en": "Honduras",
        "pt_BR": "Honduras",
        "sr-Cyrl": "Хондурас",
        "sr-Latn": "Honduras",
        "zh_TW": "宏都拉斯",
        "tr": "Honduras",
        "ro": "Honduras",
        "ar": "هندوراس",
        "fa": "هندوراس",
        "yue": "洪都拉斯"
      },
      flag: "🇭🇳",
      code: "HN",
      dialCode: "504",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Campione d'Italia",
      nameTranslations: {
        "sk": "Taliansko",
        "se": "Itália",
        "pl": "Włochy",
        "no": "Italia",
        "ja": "イタリア",
        "it": "Italia",
        "zh": "意大利",
        "nl": "Italië",
        "de": "Italien",
        "fr": "Italie",
        "es": "Italia",
        "en": "Italy",
        "pt_BR": "Itália",
        "sr-Cyrl": "Италија",
        "sr-Latn": "Italija",
        "zh_TW": "義大利",
        "tr": "İtalya",
        "ro": "Italia",
        "ar": "إيطاليا",
        "fa": "ایتالیا",
        "yue": "意大利"
      },
      flag: "🇮🇹",
      code: "IT",
      dialCode: "41",
      minLength: 13,
      maxLength: 13,
    ),
    const Country(
      name: "Jamaica",
      nameTranslations: {
        "sk": "Jamajka",
        "se": "Jamaica",
        "pl": "Jamajka",
        "no": "Jamaica",
        "ja": "ジャマイカ",
        "it": "Giamaica",
        "zh": "牙买加",
        "nl": "Jamaica",
        "de": "Jamaika",
        "fr": "Jamaïque",
        "es": "Jamaica",
        "en": "Jamaica",
        "pt_BR": "Jamaica",
        "sr-Cyrl": "Јамајка",
        "sr-Latn": "Jamajka",
        "zh_TW": "牙買加",
        "tr": "Jamaika",
        "ro": "Jamaica",
        "ar": "جامايكا",
        "fa": "جامائیکا",
        "yue": "牙買加"
      },
      flag: "🇯🇲",
      code: "JM",
      dialCode: "1876",
      minLength: 7,
      maxLength: 7,
    ),
    const Country(
      name: "Nicaragua",
      nameTranslations: {
        "sk": "Nikaragua",
        "se": "Nicaragua",
        "pl": "Nikaragua",
        "no": "Nicaragua",
        "ja": "ニカラグア",
        "it": "Nicaragua",
        "zh": "尼加拉瓜",
        "nl": "Nicaragua",
        "de": "Nicaragua",
        "fr": "Nicaragua",
        "es": "Nicaragua",
        "en": "Nicaragua",
        "pt_BR": "Nicarágua",
        "sr-Cyrl": "Никарагва",
        "sr-Latn": "Nikaragva",
        "zh_TW": "尼加拉瓜",
        "tr": "Nikaragua",
        "ro": "Nicaragua",
        "ar": "نيكاراغوا",
        "fa": "نیکاراگوئه",
        "yue": "尼加拉瓜"
      },
      flag: "🇳🇮",
      code: "NI",
      dialCode: "505",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Panama",
      nameTranslations: {
        "sk": "Panama",
        "se": "Panama",
        "pl": "Panama",
        "no": "Panama",
        "ja": "パナマ",
        "it": "Panamá",
        "zh": "巴拿马",
        "nl": "Panama",
        "de": "Panama",
        "fr": "Panama",
        "es": "Panamá",
        "en": "Panama",
        "pt_BR": "Panamá",
        "sr-Cyrl": "Панама",
        "sr-Latn": "Panama",
        "zh_TW": "巴拿馬",
        "tr": "Panama",
        "ro": "Panama",
        "ar": "بنما",
        "fa": "پاناما",
        "yue": "巴拿馬"
      },
      flag: "🇵🇦",
      code: "PA",
      dialCode: "507",
      minLength: 8,
      maxLength: 8,
    ),
    const Country(
      name: "Paraguay",
      nameTranslations: {
        "sk": "Paraguaj",
        "se": "Paraguay",
        "pl": "Paragwaj",
        "no": "Paraguay",
        "ja": "パラグアイ",
        "it": "Paraguay",
        "zh": "巴拉圭",
        "nl": "Paraguay",
        "de": "Paraguay",
        "fr": "Paraguay",
        "es": "Paraguay",
        "en": "Paraguay",
        "pt_BR": "Paraguai",
        "sr-Cyrl": "Парагвај",
        "sr-Latn": "Paragvaj",
        "zh_TW": "巴拉圭",
        "tr": "Paraguay",
        "ro": "Paraguay",
        "ar": "باراغواي",
        "fa": "پاراگوئه",
        "yue": "巴拉圭"
      },
      flag: "🇵🇾",
      code: "PY",
      dialCode: "595",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "Peru",
      nameTranslations: {
        "sk": "Peru",
        "se": "Peru",
        "pl": "Peru",
        "no": "Peru",
        "ja": "ペルー",
        "it": "Perù",
        "zh": "秘鲁",
        "nl": "Peru",
        "de": "Peru",
        "fr": "Pérou",
        "es": "Perú",
        "en": "Peru",
        "pt_BR": "Peru",
        "sr-Cyrl": "Перу",
        "sr-Latn": "Peru",
        "zh_TW": "秘鲁",
        "tr": "Peru",
        "ro": "Peru",
        "ar": "بيرو",
        "fa": "پرو",
        "yue": "秘魯"
      },
      flag: "🇵🇪",
      code: "PE",
      dialCode: "51",
      minLength: 9,
      maxLength: 9,
    ),
    const Country(
      name: "Puerto Rico",
      nameTranslations: {
        "sk": "Portoriko",
        "se": "Puerto Rico",
        "pl": "Portoryko",
        "no": "Puerto Rico",
        "ja": "プエルトリコ",
        "it": "Portorico",
        "zh": "波多黎各",
        "nl": "Puerto Rico",
        "de": "Puerto Rico",
        "fr": "Porto Rico",
        "es": "Puerto Rico",
        "en": "Puerto Rico",
        "pt_BR": "Porto Rico",
        "sr-Cyrl": "Порто Рико",
        "sr-Latn": "Porto Riko",
        "zh_TW": "波多黎各",
        "tr": "Porto Riko",
        "ro": "Puerto Rico",
        "ar": "بورتوريكو",
        "fa": "پورتوریکو",
        "yue": "波多黎各"
      },
      flag: "🇵🇷",
      code: "PR",
      dialCode: "1939",
      minLength: 15,
      maxLength: 15,
    ),
    const Country(
      name: "Spain",
      nameTranslations: {
        "sk": "Španielsko",
        "se": "Spánia",
        "pl": "Hiszpania",
        "no": "Spania",
        "ja": "スペイン",
        "it": "Spagna",
        "zh": "西班牙",
        "nl": "Spanje",
        "de": "Spanien",
        "fr": "Espagne",
        "es": "España",
        "en": "España",
        "pt_BR": "Espanha",
        "sr-Cyrl": "Шпанија",
        "sr-Latn": "Španija",
        "zh_TW": "西班牙",
        "tr": "İspanya",
        "ro": "Spania",
        "ar": "إسبانيا",
        "fa": "اسپانیا",
        "yue": "西班牙"
      },
      flag: "🇪🇸",
      code: "ES",
      dialCode: "34",
      minLength: 9,
      maxLength: 9,
    ),
    const Country(
      name: "United Kingdom",
      nameTranslations: {
        "sk": "Spojené kráľovstvo",
        "se": "Stuorra-Británnia",
        "pl": "Wielka Brytania",
        "no": "Storbritannia",
        "ja": "イギリス",
        "it": "Regno Unito",
        "zh": "英国",
        "nl": "Verenigd Koninkrijk",
        "de": "Vereinigtes Königreich",
        "fr": "Royaume-Uni",
        "es": "Reino Unido",
        "en": "United Kingdom",
        "pt_BR": "Reino Unido",
        "sr-Cyrl": "Уједињено Краљевство",
        "sr-Latn": "Ujedinjeno Kraljevstvo",
        "zh_TW": "英國",
        "tr": "Büyük Britanya ve Kuzey İrlanda Birleşik Krallığ",
        "ro": "Regatul Unit al Marii Britanii și Irlandei de Nord",
        "ar": "المملكة المتحدة",
        "fa": "بریتانیا",
        "yue": "大不列顛及北愛爾蘭聯合王國"
      },
      flag: "🇬🇧",
      code: "GB",
      dialCode: "44",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "United States",
      nameTranslations: {
        "sk": "Spojené štáty",
        "se": "Amerihká ovttastuvvan stáhtat",
        "pl": "Stany Zjednoczone",
        "no": "USA",
        "ja": "アメリカ合衆国",
        "it": "Stati Uniti",
        "zh": "美国",
        "nl": "Verenigde Staten",
        "de": "Vereinigte Staaten",
        "fr": "États-Unis",
        "es": "Estados Unidos",
        "en": "United States",
        "pt_BR": "Estados Unidos",
        "sr-Cyrl": "Сједињене Америчке Државе",
        "sr-Latn": "Sjedinjene Američke Države",
        "zh_TW": "美國",
        "tr": "Amerika Birleşik Devletleri",
        "ro": "Statele Unite ale Americii",
        "ar": "الولايات المتحدة",
        "fa": "ایالات متحده آمریکا",
        "yue": "美利堅郃眾囯"
      },
      flag: "🇺🇸",
      code: "US",
      dialCode: "1",
      minLength: 10,
      maxLength: 10,
    ),
    const Country(
      name: "Uruguay",
      nameTranslations: {
        "sk": "Uruguaj",
        "se": "Uruguay",
        "pl": "Urugwaj",
        "no": "Uruguay",
        "ja": "ウルグアイ",
        "it": "Uruguay",
        "zh": "乌拉圭",
        "nl": "Uruguay",
        "de": "Uruguay",
        "fr": "Uruguay",
        "es": "Uruguay",
        "en": "Uruguay",
        "pt_BR": "Uruguai",
        "sr-Cyrl": "Уругвај",
        "sr-Latn": "Urugvaj",
        "zh_TW": "烏拉圭",
        "tr": "Uruguay",
        "ro": "Uruguay",
        "ar": "الأوروغواي",
        "fa": "اروگوئه",
        "yue": "烏拉圭"
      },
      flag: "🇺🇾",
      code: "UY",
      dialCode: "598",
      minLength: 9,
      maxLength: 9,
    ),
    const Country(
      name: "Venezuela, Bolivarian Republic of Venezuela",
      nameTranslations: {
        "sk": "Venezuela",
        "se": "Venezuela",
        "pl": "Wenezuela",
        "no": "Venezuela",
        "ja": "ベネズエラ",
        "it": "Venezuela",
        "zh": "委内瑞拉",
        "nl": "Venezuela",
        "de": "Venezuela",
        "fr": "Venezuela",
        "es": "Venezuela",
        "en": "Venezuela",
        "pt_BR": "Venezuela",
        "sr-Cyrl": "Венецуела",
        "sr-Latn": "Venecuela",
        "zh_TW": "委內瑞拉",
        "tr": "Venezuela",
        "ro": "Venezuela",
        "ar": "فنزويلا",
        "fa": "ونزوئلا",
        "yue": "委內瑞拉（玻利瓦爾共和國）"
      },
      flag: "🇻🇪",
      code: "VE",
      dialCode: "58",
      minLength: 10,
      maxLength: 10,
    ),
  ];

}
